version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - red-financiera
    volumes:
      - web-logs:/var/log/nginx

networks:
  red-financiera:
    driver: bridge

volumes:
  web-logs:
